/**
 * VEHIQ Service-history PDF export — premium dark-on-gold header + tabular body.
 * Uses jsPDF (already installed).
 */
import jsPDF from "jspdf";

const GOLD = [201, 168, 76];
const DARK = [13, 15, 26];
const TEXT = [34, 34, 34];
const MUTED = [107, 112, 144];

const TYPE_LABELS = {
  pl: { oil: "Wymiana oleju", inspection: "Przegląd", repair: "Naprawa", tires: "Opony", insurance: "Ubezpieczenie", mot: "Badanie tech.", other: "Inne" },
  en: { oil: "Oil change", inspection: "Inspection", repair: "Repair", tires: "Tires", insurance: "Insurance", mot: "MOT", other: "Other" },
};

const STR = {
  pl: {
    title: "Historia serwisowa", generated: "Wygenerowano", page: "Strona", date: "Data", type: "Typ",
    workshop: "Warsztat", cost: "Koszt (PLN)", notes: "Uwagi", summary: "Podsumowanie kosztów",
    yearTotal: "Koszt w tym roku", lifetime: "Koszt łącznie", entries: "Liczba wpisów",
    pl: "Wynik P&L", purchase: "Cena zakupu", services: "Łączne koszty serwisowe", sale: "Cena sprzedaży",
    net: "Wynik", footer: "Wygenerowano przez VEHIQ — vehiq.pl",
    vehicle: "Pojazd", vin: "VIN", plate: "Tablice", mileage: "Przebieg",
  },
  en: {
    title: "Service history", generated: "Generated", page: "Page", date: "Date", type: "Type",
    workshop: "Workshop", cost: "Cost (PLN)", notes: "Notes", summary: "Cost summary",
    yearTotal: "This year", lifetime: "Lifetime total", entries: "Entries",
    pl: "P&L Result", purchase: "Purchase price", services: "Total service cost", sale: "Sale price",
    net: "Net", footer: "Generated by VEHIQ — vehiq.pl",
    vehicle: "Vehicle", vin: "VIN", plate: "Plate", mileage: "Mileage",
  },
};

function fmt(n) { return (Number(n) || 0).toLocaleString("pl-PL", { maximumFractionDigits: 2 }); }
function dateStr() { const d = new Date(); return d.toISOString().slice(0, 16).replace("T", " "); }

export function exportServicePdf({ vehicle, entries, pl: plData, lang = "pl" }) {
  const L = STR[lang] || STR.pl;
  const TL = TYPE_LABELS[lang] || TYPE_LABELS.pl;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const M = 14;
  let y = 0;

  // ---------- HEADER (dark + gold) ----------
  doc.setFillColor(...DARK);
  doc.rect(0, 0, W, 30, "F");
  // Logo box
  doc.setFillColor(...GOLD);
  doc.rect(M, 9, 11, 12, "F");
  doc.setTextColor(...DARK);
  doc.setFont("times", "bold");
  doc.setFontSize(15);
  doc.text("V", M + 5.5, 17.5, { align: "center" });
  // Brand
  doc.setTextColor(244, 241, 236);
  doc.setFont("times", "normal");
  doc.setFontSize(20);
  doc.text("VEHIQ", M + 16, 17);
  doc.setTextColor(...GOLD);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.text("VIRTUAL GARAGE", M + 16, 22);
  // Title + generated date
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(244, 241, 236);
  doc.text(L.title.toUpperCase(), W - M, 14, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...GOLD);
  doc.text(`${L.generated}: ${dateStr()}`, W - M, 20, { align: "right" });

  y = 40;

  // ---------- VEHICLE BLOCK ----------
  doc.setTextColor(...TEXT);
  doc.setFont("times", "italic");
  doc.setFontSize(22);
  const vehicleLabel = `${vehicle.make || ""} ${vehicle.model || ""} ${vehicle.year ? `· ${vehicle.year}` : ""}`.trim();
  doc.text(vehicleLabel, M, y);

  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...MUTED);
  const meta = [];
  if (vehicle.vin) meta.push(`${L.vin}: ${vehicle.vin}`);
  if (vehicle.plate) meta.push(`${L.plate}: ${vehicle.plate}`);
  if (vehicle.mileage_current) meta.push(`${L.mileage}: ${vehicle.mileage_current.toLocaleString("pl-PL")} km`);
  if (vehicle.engine) meta.push(vehicle.engine);
  if (vehicle.fuel) meta.push(vehicle.fuel.toUpperCase());
  doc.text(meta.join("   ·   "), M, y);

  y += 8;
  doc.setDrawColor(...GOLD);
  doc.setLineWidth(0.4);
  doc.line(M, y, W - M, y);
  y += 8;

  // ---------- SUMMARY CARDS ----------
  const totalLifetime = entries.reduce((s, e) => s + (Number(e.cost) || 0), 0);
  const yr = new Date().getFullYear();
  const totalYear = entries.filter(e => (e.date || "").startsWith(String(yr))).reduce((s, e) => s + (Number(e.cost) || 0), 0);

  const cardW = (W - 2 * M - 4) / 3;
  const cardH = 18;
  const drawCard = (x, label, value) => {
    doc.setFillColor(248, 246, 240);
    doc.setDrawColor(...GOLD);
    doc.rect(x, y, cardW, cardH, "FD");
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.text(label.toUpperCase(), x + 3, y + 5);
    doc.setTextColor(...DARK);
    doc.setFont("times", "bold");
    doc.setFontSize(13);
    doc.text(value, x + 3, y + 13);
  };
  drawCard(M, L.yearTotal, `${fmt(totalYear)} PLN`);
  drawCard(M + cardW + 2, L.lifetime, `${fmt(totalLifetime)} PLN`);
  drawCard(M + 2 * (cardW + 2), L.entries, String(entries.length));
  y += cardH + 8;

  // ---------- ENTRIES TABLE ----------
  const cols = [
    { label: L.date, w: 24 },
    { label: L.type, w: 30 },
    { label: L.workshop, w: 50 },
    { label: L.cost, w: 26, align: "right" },
    { label: L.notes, w: W - 2 * M - 24 - 30 - 50 - 26 },
  ];
  // header
  doc.setFillColor(...DARK);
  doc.rect(M, y, W - 2 * M, 8, "F");
  doc.setTextColor(...GOLD);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  let cx = M + 2;
  cols.forEach(c => {
    doc.text(c.label.toUpperCase(), c.align === "right" ? cx + c.w - 2 : cx, y + 5.5, { align: c.align || "left" });
    cx += c.w;
  });
  y += 10;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...TEXT);

  const sorted = [...entries].sort((a, b) => (b.date || "").localeCompare(a.date || ""));
  for (const e of sorted) {
    if (y > H - 30) {
      addFooter(doc, L);
      doc.addPage();
      y = 20;
    }
    let cx = M + 2;
    const cells = [
      (e.date || "").slice(0, 10),
      TL[e.type] || e.type,
      e.workshop || "—",
      fmt(e.cost),
      (e.notes || "").slice(0, 60),
    ];
    cells.forEach((val, i) => {
      const c = cols[i];
      if (c.align === "right") doc.text(String(val), cx + c.w - 2, y, { align: "right" });
      else doc.text(String(val), cx, y);
      cx += c.w;
    });
    y += 6;
    doc.setDrawColor(230, 226, 215);
    doc.setLineWidth(0.1);
    doc.line(M, y - 2, W - M, y - 2);
  }

  // ---------- P&L summary ----------
  if (plData && (plData.purchase_price || plData.sale_price || plData.total_service_cost)) {
    if (y > H - 50) { addFooter(doc, L); doc.addPage(); y = 20; }
    y += 8;
    doc.setFont("times", "bold");
    doc.setFontSize(15);
    doc.setTextColor(...DARK);
    doc.text(L.pl, M, y);
    y += 6;
    const isProfit = (plData.net_result || 0) >= 0;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...TEXT);
    const rows = [
      [L.purchase, `${fmt(plData.purchase_price)} PLN`],
      [L.services, `${fmt(plData.total_service_cost)} PLN`],
      [L.sale, plData.sale_price ? `${fmt(plData.sale_price)} PLN` : "—"],
    ];
    rows.forEach(([k, v]) => {
      doc.text(k, M, y);
      doc.text(v, W - M, y, { align: "right" });
      y += 6;
    });
    doc.setDrawColor(...GOLD);
    doc.line(M, y, W - M, y);
    y += 6;
    doc.setFont("times", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...(isProfit ? GOLD : [200, 60, 60]));
    doc.text(`${L.net}: ${fmt(plData.net_result)} PLN`, W - M, y, { align: "right" });
    y += 4;
  }

  addFooter(doc, L);

  const fname = `VEHIQ_${(vehicle.make || "").replace(/\s+/g, "")}_${(vehicle.model || "").replace(/\s+/g, "")}_${vehicle.year || ""}_${lang === "en" ? "service" : "serwis"}.pdf`;
  doc.save(fname);
}

function addFooter(doc, L) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  doc.setDrawColor(201, 168, 76);
  doc.setLineWidth(0.3);
  doc.line(14, H - 14, W - 14, H - 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(107, 112, 144);
  doc.text(L.footer, 14, H - 8);
  const page = doc.internal.getNumberOfPages();
  doc.text(`${L.page} ${page}`, W - 14, H - 8, { align: "right" });
}
